

# Request
PathPlanningAlgos/Goal goal
PathPlanningAlgos/Robot robot
PathPlanningAlgos/GaussianParams[] params
PathPlanningAlgos/ObstacleList[] values

---

# Response
trajectory_msgs/JointTrajectory trajectory
float64[] arc_length
